<a href="https://colab.research.google.com/github/drdave-teaching/OPIM3510-BDA1/blob/main/M1_Python_Bootcamp/Week01_02_Python_Basics/Project1_SubsettingData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Individual Assignment: Subsetting Data


**OPIM Python Bootcamp - University of Connecticut**

---------------------------------

In this assignment, we will explore selecting data based on a condition from the [California Housing](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_california_housing.html) dataset. There are many different versions of this dataset floating round - be careful! Sometimes names are written in `lowercase`, `UPPERCASE` or `camelCase`. To be sure, after you read a dataset, use `df.info()` or `df.columns` to check the column names. Of course you can always rename them if you want to!

In this notebook, you will do data subsetting of various rows and columns. For simplicity and so that you can check your work, we will only keep the first 10 rows as a subset to work with. Mock rubric below (not graded - just for your own knowledge.)

**100 pts total, 10 pts each.** For each question, print BOTH the output and print the shape to confirm your answer. Otherwise, only half credit. Be careful and remember that Python counts from 0 not 1!

* 1) Select the first 5 rows and all columns.
* 2) Select the last 6 rows and all columns.
* 3) Select the third through fifth row and the first three columns.
* 4) Select the fouth through eighth row and the last three columns.
* 5) Select the second through eighth row and the seventh, eighth and ninth column.
* 6) Select the third through eighth row and the second, third and fourth column.
* 7) Select the third through eighth row and the second, third and fifth column.
* 8) Select the first through eighth row and the sixth, seventh and ninth column.
* 9) Select the fifth column and all rows. Take the transpose of this vector.
* 10) Select the last two column and all rows. Take the transpose of this array.

[TowardsDataScience](https://towardsdatascience.com/how-to-use-loc-and-iloc-for-selecting-data-in-pandas-bd09cb4c3d79) and [StackOverflow](https://stackoverflow.com/questions/22927181/selecting-specific-rows-and-columns-from-numpy-array) are your friends❗

Try not to use ChatGPT too much - the code has to come out of YOUR fingers, not a chatbot's neurons.

# Import the data from Github
You can use `pandas` to read .csv files straight from GitHub - no download needed.

In [1]:
import pandas as pd
DATA_URL = "https://raw.githubusercontent.com/drdave-teaching/OPIM3510-BDA1/main/data/california_housing_train.csv"
df = pd.read_csv(DATA_URL)
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [2]:
# keep the first 10 rows per simplicity
df = df[0:10]
df # remember that Python counts from 0!

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
5,-114.58,33.63,29.0,1387.0,236.0,671.0,239.0,3.3438,74000.0
6,-114.58,33.61,25.0,2907.0,680.0,1841.0,633.0,2.6768,82400.0
7,-114.59,34.83,41.0,812.0,168.0,375.0,158.0,1.7083,48500.0
8,-114.59,33.61,34.0,4789.0,1175.0,3134.0,1056.0,2.1782,58400.0
9,-114.60,34.83,46.0,1497.0,309.0,787.0,271.0,2.1908,48100.0

Now just use this simple `df` for the rest of the notebook. You don't have to keep reading in `df` over and over again.

Remember there can be a lot of ways to code this - which can be great and frustrating! Choose the method that makes sense to you, and be aware of other methods even if you don't use them.

In [3]:
# good luck! use nice headers for each question so that it is easy to grade. like below!

# Q1
1) Select the first 5 rows and all columns.

In [4]:
# make sure you have nice comments so it's easy to follow

# Q2