<a href="https://colab.research.google.com/github/drdave-teaching/OPIM3510-BDA1/blob/main/M1_Python_Bootcamp/Week01_02_Python_Basics/Project1_SubsettingData_answers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Individual Assignment: Subsetting Data


**OPIM Python Bootcamp - University of Connecticut**

---------------------------------

In this assignment, we will explore selecting data based on a condition from the [California Housing](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_california_housing.html) dataset. There are many different versions of this dataset floating round - be careful! Sometimes names are written in `lowercase`, `UPPERCASE` or `camelCase`. To be sure, after you read a dataset, use `df.info()` or `df.columns` to check the column names. Of course you can always rename them if you want to!

In this notebook, you will do data subsetting of various rows and columns. For simplicity and so that you can check your work, we will only keep the first 10 rows as a subset to work with. Mock rubric below (not graded - just for your own knowledge.)

**100 pts total, 10 pts each.** For each question, print BOTH the output and print the shape to confirm your answer. Otherwise, only half credit. Be careful and remember that Python counts from 0 not 1!

* 1) Select the first 5 rows and all columns.
* 2) Select the last 6 rows and all columns.
* 3) Select the third through fifth row and the first three columns.
* 4) Select the fouth through eighth row and the last three columns.
* 5) Select the second through eighth row and the seventh, eighth and ninth column.
* 6) Select the third through eighth row and the second, third and fourth column.
* 7) Select the third through eighth row and the second, third and fifth column.
* 8) Select the first through eighth row and the sixth, seventh and ninth column.
* 9) Select the fifth column and all rows. Take the transpose of this vector.
* 10) Select the last two column and all rows. Take the transpose of this array.

[TowardsDataScience](https://towardsdatascience.com/how-to-use-loc-and-iloc-for-selecting-data-in-pandas-bd09cb4c3d79) and [StackOverflow](https://stackoverflow.com/questions/22927181/selecting-specific-rows-and-columns-from-numpy-array) are your friends❗

Try not to use ChatGPT too much - the code has to come out of YOUR fingers, not a chatbot's neurons.

# Read the data

In [1]:
import pandas as pd
DATA_URL = "https://raw.githubusercontent.com/drdave-teaching/OPIM3510-BDA1/main/data/california_housing_train.csv"
df = pd.read_csv(DATA_URL)
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [2]:
# keep the first 10 rows for simplicity (so you can check your work by eye)
df = df[0:10]
df # remember that Python counts from 0!

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
5,-114.58,33.63,29.0,1387.0,236.0,671.0,239.0,3.3438,74000.0
6,-114.58,33.61,25.0,2907.0,680.0,1841.0,633.0,2.6768,82400.0
7,-114.59,34.83,41.0,812.0,168.0,375.0,158.0,1.7083,48500.0
8,-114.59,33.61,34.0,4789.0,1175.0,3134.0,1056.0,2.1782,58400.0
9,-114.60,34.83,46.0,1497.0,309.0,787.0,271.0,2.1908,48100.0

In [3]:
# good luck! use nice headers for each question so that it is easy to grade. like below!

# Q1: Select the first 5 rows and all columns.

In [4]:
Q1 = df[:5] # select the first 5 rows and all columns
print(Q1) # print the output
print(Q1.shape) # show the shape (5, 9)

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0
1    -114.47     34.40                19.0       7650.0          1901.0
2    -114.56     33.69                17.0        720.0           174.0
3    -114.57     33.64                14.0       1501.0           337.0
4    -114.57     33.57                20.0       1454.0           326.0

   population  households  median_income  median_house_value
0      1015.0       472.0         1.4936             66900.0
1      1129.0       463.0         1.8200             80100.0
2       333.0       117.0         1.6509             85700.0
3       515.0       226.0         3.1917             73400.0
4       624.0       262.0         1.9250             65500.0
(5, 9)

# Q2: Select the last 6 rows and all columns.

In [5]:
Q2 = df[-6:] # select the last 6 rows and all columns
print(Q2) # print the output
print(Q2.shape) # show the shape (6, 9)

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
4    -114.57     33.57                20.0       1454.0           326.0
5    -114.58     33.63                29.0       1387.0           236.0
6    -114.58     33.61                25.0       2907.0           680.0
7    -114.59     34.83                41.0        812.0           168.0
8    -114.59     33.61                34.0       4789.0          1175.0
9    -114.60     34.83                46.0       1497.0           309.0

   population  households  median_income  median_house_value
4       624.0       262.0         1.9250             65500.0
5       671.0       239.0         3.3438             74000.0
6      1841.0       633.0         2.6768             82400.0
7       375.0       158.0         1.7083             48500.0
8      3134.0      1056.0         2.1782             58400.0
9       787.0       271.0         2.1908             48100.0
(6, 9)

# Q3: Select the third through fifth row and the first three columns.

In [6]:
Q3 = df.iloc[2:5, :3] # select the 3rd through 5th row and first three columns
print(Q3) # print the output
print(Q3.shape) # show the shape (3, 3)

   longitude  latitude  housing_median_age
2    -114.56     33.69                17.0
3    -114.57     33.64                14.0
4    -114.57     33.57                20.0
(3, 3)

# Q4: Select the fourth through eighth row and the last three columns.

In [7]:
Q4 = df.iloc[3:8, -3:] # select the 4th through 8th row and last three columns
print(Q4) # print the output
print(Q4.shape) # show the shape (5, 3)

   households  median_income  median_house_value
3       226.0         3.1917             73400.0
4       262.0         1.9250             65500.0
5       239.0         3.3438             74000.0
6       633.0         2.6768             82400.0
7       158.0         1.7083             48500.0
(5, 3)

# Q5: Select the second through eighth row and the seventh, eighth and ninth column.

In [8]:
Q5 = df.iloc[1:8, 6:9] # select the 2nd through 8th row and 7th, 8th and 9th column
print(Q5) # print the output
print(Q5.shape) # show the shape (7, 3)

   households  median_income  median_house_value
1       463.0         1.8200             80100.0
2       117.0         1.6509             85700.0
3       226.0         3.1917             73400.0
4       262.0         1.9250             65500.0
5       239.0         3.3438             74000.0
6       633.0         2.6768             82400.0
7       158.0         1.7083             48500.0
(7, 3)

# Q6: Select the third through eighth row and the second, third and fourth column.

In [9]:
Q6 = df.iloc[2:8, 1:4] # select the 3rd through 8th row and 2nd, 3rd and 4th column
print(Q6) # print the output
print(Q6.shape) # show the shape (6, 3)

   latitude  housing_median_age  total_rooms
2     33.69                17.0        720.0
3     33.64                14.0       1501.0
4     33.57                20.0       1454.0
5     33.63                29.0       1387.0
6     33.61                25.0       2907.0
7     34.83                41.0        812.0
(6, 3)

# Q7: Select the third through eighth row and the second, third and fifth column.

In [10]:
Q7 = df.iloc[2:8, [1, 2, 4]] # select the 3rd through 8th row and 2nd, 3rd and 5th column
print(Q7) # print the output
print(Q7.shape) # show the shape (6, 3)

   latitude  housing_median_age  total_bedrooms
2     33.69                17.0           174.0
3     33.64                14.0           337.0
4     33.57                20.0           326.0
5     33.63                29.0           236.0
6     33.61                25.0           680.0
7     34.83                41.0           168.0
(6, 3)

# Q8: Select the first through eighth row and the sixth, seventh and ninth column.

In [11]:
Q8 = df.iloc[0:8, [5, 6, 8]] # select the 1st through 8th row and 6th, 7th and 9th column
print(Q8) # print the output
print(Q8.shape) # show the shape (8, 3)

   population  households  median_house_value
0      1015.0       472.0             66900.0
1      1129.0       463.0             80100.0
2       333.0       117.0             85700.0
3       515.0       226.0             73400.0
4       624.0       262.0             65500.0
5       671.0       239.0             74000.0
6      1841.0       633.0             82400.0
7       375.0       158.0             48500.0
(8, 3)

# Q9: Select the fifth column and all rows. Take the transpose of this vector.

In [12]:
Q9 = df.iloc[:, [4]] # select the 5th column and all rows
print(Q9) # print the output
print(Q9.shape) # print the shape (10, 1)

#print(Q9.T) # transpose of this vector
print(Q9.T.shape) # show the shape (1, 10)

   total_bedrooms
0          1283.0
1          1901.0
2           174.0
3           337.0
4           326.0
5           236.0
6           680.0
7           168.0
8          1175.0
9           309.0
(10, 1)
(1, 10)

# Q10: Select the last two column and all rows. Take the transpose of this array.

In [13]:
Q10 = df.iloc[:, -2:] # select the last 2 column and all rows
print(Q10) # print the output
print(Q10.shape) # show the shape (10, 2) before transpose

#print(Q10.T) # transpose of this array
print(Q10.T.shape) # show the shape (2, 10)

   median_income  median_house_value
0         1.4936             66900.0
1         1.8200             80100.0
2         1.6509             85700.0
3         3.1917             73400.0
4         1.9250             65500.0
5         3.3438             74000.0
6         2.6768             82400.0
7         1.7083             48500.0
8         2.1782             58400.0
9         2.1908             48100.0
(10, 2)
(2, 10)